# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gitea/v1/messages.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("gitea/v1/messages.proto", :syntax => :proto3) do
    add_message "gitea.v1.GiteaRequest" do
      optional :name, :string, 1, json_name: "name"
    end
    add_message "gitea.v1.GiteaResponse" do
      optional :giteaing, :string, 1, json_name: "giteaing"
    end
    add_message "gitea.v1.IntroduceRequest" do
      optional :name, :string, 1, json_name: "name"
    end
    add_message "gitea.v1.IntroduceResponse" do
      optional :sentence, :string, 1, json_name: "sentence"
    end
  end
end

module Gitea
  module V1
    GiteaRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("gitea.v1.GiteaRequest").msgclass
    GiteaResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("gitea.v1.GiteaResponse").msgclass
    IntroduceRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("gitea.v1.IntroduceRequest").msgclass
    IntroduceResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("gitea.v1.IntroduceResponse").msgclass
  end
end
