# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gitea/v1/services.proto

require 'google/protobuf'

require 'gitea/v1/messages_pb'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("gitea/v1/services.proto", :syntax => :proto3) do
  end
end

module Gitea
  module V1
  end
end
