# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: gitea/v1/services.proto for package 'gitea.v1'

require 'grpc'
require 'gitea/v1/services_pb'

module Gitea
  module V1
    module GiteaService
      class Service

        include ::GRPC::GenericService

        self.marshal_class_method = :encode
        self.unmarshal_class_method = :decode
        self.service_name = 'gitea.v1.GiteaService'

        rpc :Gitea, ::Gitea::V1::GiteaRequest, ::Gitea::V1::GiteaResponse
        # Introduce is a server-streaming request demo.  This method allows for a single request that will return a series
        # of responses
        rpc :Introduce, ::Gitea::V1::IntroduceRequest, stream(::Gitea::V1::IntroduceResponse)
      end

      Stub = Service.rpc_stub_class
    end
  end
end
