# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ping/v1/messages.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("ping/v1/messages.proto", :syntax => :proto3) do
    add_message "ping.v1.PingRequest" do
      optional :data, :string, 1, json_name: "data"
    end
    add_message "ping.v1.PingResponse" do
      optional :data, :string, 1, json_name: "data"
    end
  end
end

module Ping
  module V1
    PingRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("ping.v1.PingRequest").msgclass
    PingResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("ping.v1.PingResponse").msgclass
  end
end
