# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ping/v1/services.proto

require 'google/protobuf'

require 'ping/v1/messages_pb'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("ping/v1/services.proto", :syntax => :proto3) do
  end
end

module Ping
  module V1
  end
end
