# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: ping/v1/services.proto for package 'ping.v1'

require 'grpc'
require 'ping/v1/services_pb'

module Ping
  module V1
    module PingService
      class Service

        include ::GRPC::GenericService

        self.marshal_class_method = :encode
        self.unmarshal_class_method = :decode
        self.service_name = 'ping.v1.PingService'

        rpc :Ping, ::Ping::V1::PingRequest, ::Ping::V1::PingResponse
      end

      Stub = Service.rpc_stub_class
    end
  end
end
